services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /storage/data/kavita/config:/config
      - /storage/media/books:/books
      - /storage/media/comics:/comics
      - /storage/media/manga:/manga
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`comics.alimunee.com`)"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  proxy:
    external: true
