services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_ENABLE_SECURITY=${SECURITY_ENABLED:-false}
      - SECURITY_ENABLELOGIN=${SECURITY_ENABLED:-false}
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=en_US
      - SYSTEM_DEFAULTLOCALE=en-US
      - UI_APPNAME=Stirling PDF
      - UI_HOMEDESCRIPTION=Your locally hosted one-stop-shop for all your PDF needs
      - UI_APPNAMENAVBAR=Stirling PDF
      - SYSTEM_MAXFILESIZE=100
      - METRICS_ENABLED=true
      - SYSTEM_GOOGLEVISIBILITY=false
      - SHOW_SURVEY=false
      - SYSTEM_CUSTOMSTATICFILEPATH=/customFiles/static/
      - PUID=1000
      - PGID=1000
      - UMASK=022
    volumes:
      - /storage/data/stirling-pdf/tessdata:/usr/share/tessdata:rw
      - /storage/data/stirling-pdf/config:/configs:rw
      - /storage/data/stirling-pdf/logs:/logs:rw
      - /storage/data/stirling-pdf/customFiles:/customFiles:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.alimunee.com`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  proxy:
    external: true
