services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SECURITY_ENABLELOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=${ADMIN_USERNAME:-admin}
      - SECURITY_INITIALLOGIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=en_US
      - SYSTEM_DEFAULTLOCALE=en-US
      - SYSTEM_MAXFILESIZE=100
      - METRICS_ENABLED=true
      - SYSTEM_GOOGLEVISIBILITY=false
      - SYSTEM_CUSTOMSTATICFILEPATH=/customFiles/static/
      - MAIL_ENABLED=true
      - MAIL_FROM=stirling-pdf@alimunee.com
      - MAIL_ENABLEINVITES=true
      - MAIL_HOST=postfix
      - MAIL_PORT=25
    volumes:
      - /storage/data/stirling-pdf/tessdata:/usr/share/tessdata:rw
      - /storage/data/stirling-pdf/config:/configs:rw
      - /storage/data/stirling-pdf/logs:/logs:rw
      - /storage/data/stirling-pdf/pipeline:/pipeline:rw
      - /storage/data/stirling-pdf/customFiles:/customFiles:rw
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - proxy
      - mail_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.alimunee.com`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  proxy:
    external: true
  mail_network:
    external: true
