services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vert.rule=Host(`convert.alimunee.com`)"
      - "traefik.http.services.vert.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  proxy:
    external: true
