#!/usr/bin/env bash
# Register the Forgejo Actions runner and (re)generate its config.
#
# Idempotent: the runner secret is created once and reused, and `forgejo-cli actions
# register` is an upsert, so re-running this on a live runner does not invalidate it.
#
# The secret and the generated config stay in /storage/data/forgejo/runner/ (not in
# this repository, which is public). The UUID is derived from the secret, so it lives
# there too rather than being committed.
set -euo pipefail

STATE_DIR=/storage/data/forgejo/runner
SECRET_FILE="${STATE_DIR}/runner-secret"
SECRET="${SECRET_FILE}"

RUNNER_NAME="${RUNNER_NAME:-redripper-runner}"
LABELS="${LABELS:-ubuntu-latest:docker://node:22-bookworm,ubuntu-22.04:docker://node:22-bookworm}"

mkdir -p "${STATE_DIR}/act"
chmod 700 "${STATE_DIR}"

if [[ -s "${SECRET_FILE}" ]]; then
  echo "Reusing existing runner secret"
else
  # Adopt the secret generated during the initial deploy, if it is still around.
  if [[ -s /storage/data/forgejo/.runner_secret ]]; then
    mv /storage/data/forgejo/.runner_secret "${SECRET_FILE}"
    echo "Adopted staged runner secret"
  else
    docker exec -u git forgejo forgejo forgejo-cli actions generate-secret > "${SECRET_FILE}"
    echo "Generated new runner secret"
  fi
  chmod 600 "${SECRET_FILE}"
fi

UUID="$(docker exec -u git forgejo forgejo forgejo-cli actions register \
  --name "${RUNNER_NAME}" --secret "$(cat "${SECRET_FILE}")" --labels "${LABELS}" | tr -d '\r\n')"
if [[ -z "${UUID}" ]]; then
  echo "ERROR: registration returned no UUID" >&2
  exit 1
fi
echo "Registered runner '${RUNNER_NAME}' as ${UUID}"

cat > "${STATE_DIR}/config.yaml" <<EOF
# Generated by services/forgejo/setup-runner.sh - do not commit (contains the runner secret).
log:
  level: info

runner:
  capacity: 1
  timeout: 3h
  labels:
    - ubuntu-latest:docker://node:22-bookworm
    - ubuntu-22.04:docker://node:22-bookworm

container:
  # Join the stack network so job containers can resolve the \`forgejo\` service name.
  network: forgejo_internal
  # Empty => /workspace inside the job container.
  workdir_parent: ""
  valid_volumes: []
  # "-" => do not hand the Docker socket to job containers. The runner itself holds it.
  docker_host: "-"

host:
  # Host-side workspace root. Must match the runner's own view (same-path bind mount),
  # because job containers are created by the host daemon as siblings of this container.
  workdir_parent: /storage/data/forgejo/runner/act

server:
  connections:
    redripper:
      url: http://forgejo:3000
      uuid: ${UUID}
      token: $(cat "${SECRET_FILE}")
EOF
chmod 600 "${STATE_DIR}/config.yaml"
echo "Wrote ${STATE_DIR}/config.yaml"

echo
echo "Now start it:  docker compose up -d forgejo-runner"
