name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Photos/videos on HDD for capacity
      - /storage/Immich/uploads:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - proxy
      - immich_internal
      - mail_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`photos.alimunee.com`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.docker.network=proxy"
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # GPU-accelerated image for CUDA support
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    volumes:
      - /storage/data/immich/model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      # GPU-specific environment variables
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      # GPU device access (same as Jellyfin)
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    group_add:
      - "105" # render group for GPU access
      - "39" # video group for GPU access
    restart: unless-stopped
    networks:
      - immich_internal
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 1G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    networks:
      - immich_internal
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # Uncomment if your database storage is on HDD instead of SSD
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Database on NVMe for performance
      - /storage/data/immich/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    shm_size: 128mb
    networks:
      - immich_internal
      - db_network
    restart: unless-stopped

volumes:
  model-cache:


networks:
  proxy:
    external: true
  immich_internal:
    driver: bridge
  db_network:
    external: true
  mail_network:
    external: true
    name: mail_network
