services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.alimunee.com
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=cloud.alimunee.com
      - OVERWRITECLIURL=https://cloud.alimunee.com
      - PHP_MEMORY_LIMIT=2G
      - PHP_UPLOAD_LIMIT=16G
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.0.0.0/8
    volumes:
      - /storage/data/nextcloud/html:/var/www/html
      - /storage/nextcloud:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - nextcloud_internal
      - mail_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.alimunee.com`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud-headers.headers.customrequestheaders.X-Forwarded-Host=cloud.alimunee.com"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud-secure.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-secure,nextcloud-headers,nextcloud-caldav"
      - "watchtower.enable=true"
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-db:
    image: postgres:17-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /storage/data/nextcloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nextcloud_internal
      - db_network
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    env_file:
      - .env
    command: >
      redis-server
      --requirepass ${REDIS_HOST_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - /storage/data/nextcloud/redis:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nextcloud_internal
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_HOST_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /storage/data/nextcloud/html:/var/www/html
      - /storage/nextcloud:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /cron.sh
    networks:
      - nextcloud_internal
    depends_on:
      - nextcloud
      - nextcloud-db
      - nextcloud-redis

networks:
  proxy:
    external: true
  nextcloud_internal:
    name: nextcloud_internal
    driver: bridge
  db_network:
    external: true
    name: db_network
  mail_network:
    external: true
    name: mail_network
