services:
  flood:
    image: jesec/flood:latest
    container_name: flood
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /storage/data/flood:/config
      - /storage/media/downloads:/downloads
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flood.rule=Host(`flood.alimunee.com`)"
      - "traefik.http.services.flood.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
