services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /storage/data/beszel:/beszel_data
      - /storage/data/beszel/socket:/beszel_socket
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ 'CMD', '/beszel', 'health', '--url', 'http://localhost:8090' ]
      start_period: 5s
      interval: 120s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`monitor.alimunee.com`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.docker.network=proxy"
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /storage/data/beszel/agent:/var/lib/beszel-agent
      - /storage/data/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      # Monitor additional filesystems
      - /storage:/extra-filesystems/storage:ro
    environment:
      - TZ=America/New_York
      - LISTEN=/beszel_socket/beszel.sock
      - HUB_URL=http://localhost:8090
      # These will be set in .env file
      - TOKEN=${BESZEL_TOKEN}
      - KEY=${BESZEL_KEY}
    healthcheck:
      test: [ 'CMD', '/agent', 'health' ]
      interval: 120s
      timeout: 10s
      retries: 3
    labels:
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
