services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: cloudreve
    restart: unless-stopped
    depends_on:
      - database
      - redis
    env_file:
      - .env
    environment:
      - CR_CONF_Database.Type=postgres
      - CR_CONF_Database.Host=database
      - CR_CONF_Database.User=cloudreve
      - CR_CONF_Database.Name=cloudreve
      - CR_CONF_Database.Port=5432
      - CR_CONF_Database.Password=${POSTGRES_PASSWORD:-cloudreve}
      - CR_CONF_Redis.Server=redis:6379
    volumes:
      - /storage/data/cloudreve:/cloudreve/data
      - /storage/data/cloudreve/uploads:/cloudreve/uploads
    networks:
      - proxy
      - cloudreve_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloudreve.rule=Host(`files.alimunee.com`)"
      - "traefik.http.services.cloudreve.loadbalancer.server.port=5212"
      - "traefik.docker.network=proxy"
      # Zitadel SSO integration (commented out until configured)
      # - "traefik.http.routers.cloudreve.middlewares=Zitadel@docker"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5212" ]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: postgres:17
    container_name: cloudreve_database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=cloudreve
      - POSTGRES_DB=cloudreve
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cloudreve}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - /storage/data/cloudreve/database:/var/lib/postgresql/data
    networks:
      - cloudreve_internal
      - db_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudreve -d cloudreve" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: cloudreve_redis
    restart: unless-stopped
    volumes:
      - /storage/data/cloudreve/redis:/data
    networks:
      - cloudreve_internal
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy:
    external: true
  cloudreve_internal:
    name: cloudreve_internal
    driver: bridge
  db_network:
    external: true
